export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_END = 'FETCH_USER_END';
export const ERROR_USER = 'ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
