export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_END = 'FETCH_USER_END';
export const ERROR_USER = 'ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_END = 'CHANGE_PASSWORD_END';
export const ERROR_CHANGE_PASSWORD = 'ERROR_CHANGE_PASSWORD';
